FROM emscripten/emsdk as build_nts
WORKDIR /app
COPY mtl mtl
COPY nano nano
COPY CMakeLists.txt .
WORKDIR /app/build
RUN emcmake cmake .. -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=/app/out \
    && cmake --build . --config Release

FROM node:12-alpine as build_web
WORKDIR /app
COPY bonus/web_playground/package*.json .
RUN npm ci
COPY bonus/web_playground .
RUN npm run build
COPY --from=build_nts /app/out public

FROM svenstaro/miniserve as serve
WORKDIR /app
COPY --from=build_web /app/public .
EXPOSE 8080
CMD [ ".", "--index", "index.html" ]
